spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/longjiang?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
  mail:
    host: smtp.qq.com
    port: 465
    username:
    password:
    protocol: smtps
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  redis:
    database: 0
    port: 6379
    host: localhost
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 1s #设置MQ的连接超时事件
    template:
      retry:
        enabled: true #开启超时重试
        initial-interval: 200ms #失败后的初始等待事件
        multiplier: 1 #失败后下次的等待时长倍数
        max-attempts: 3 #最大重试次数
    publisher-confirm-type: correlated #开启pulisher confirm机制 ,并选用异步等待
    listener:
      simple:
        acknowledge-mode: auto
        retry:
          enabled: true #开启失败重试
          initial-interval: 100ms #间隔
          max-attempts: 3 #最大重试次数
  


server:
  port: 8080
  servlet:
    context-path: "/LongJiang"
mybatis:
  mapper-locations: classpath:=mapper/*.xml
  type-aliases-package: com.longjiang.Entity
  configuration:
        use-generated-keys: true
        map-underscore-to-camel-case: true
longjiang :
  path :
    domain : http://localhost:8080
    upload : E:/LongJiangTest