spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/longjiang?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
server:
  port: 8080
mybatis:
  mapper-locations: classpath:=mapper/*.xml
  type-aliases-package: com.longjiang.Entity
  configuration:
        use-generated-keys: true
        map-underscore-to-camel-case: true
